apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: "$APP_IMAGE"
        env:
        - name: APP_NAME
          value: "$APP_NAME"
        - name: PORT
          value: "8080"
        - name: PEER_ENDPOINT
          value: "$PEER-$ORG.$NAMESPACE.localho.st:443"
        - name: PEER_HOST_ALIAS
          value: "$PEER-$ORG.$NAMESPACE.localho.st"
        - name: TLS_CERT_PATH
          value: /config/cacert.pem
        - name: KEY_DIRECTORY_PATH
          value: /config/user-key
        - name: CERT_DIRECTORY_PATH
          value: /config/user-cert
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /config/cacert.pem
          name: ca-cert
          subPath: cacert.pem
          readOnly: true
        - mountPath: /config/user-key/key.pem
          subPath: key.pem
          name: user
          readOnly: true
        - mountPath: /config/user-cert/cert.pem
          subPath: cert.pem
          name: user
          readOnly: true
      volumes:
      - name: ca-cert
        secret:
          secretName: "$ORG-$PEER-cacert" # managed by operator
      - name: user
        secret:
          secretName: "$ORG-$USER" # managed by operator

---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
    service: app
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: app
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: app-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "app.localho.st"
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: app
spec:
  hosts:
  - "app.localho.st"
  gateways:
  - app-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8080
        host: app 
