apiVersion: v1
kind: Namespace
metadata:
  name: hlf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: hlf 
imagePullSecrets:
- name: pull-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-ci-manage-hlf
  namespace: hlf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default 
  namespace: gitlab-ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-ci-manage-hlf
rules:
- apiGroups: ["hlf.kungfusoftware.es"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-ci-manage-hlf
subjects:
- kind: ServiceAccount
  name: default 
  namespace: gitlab-ci
roleRef:
  kind: ClusterRole
  name: gitlab-ci-manage-hlf
